import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  server: {
    host: true, // expose the dev server on the LAN
    watch: {
      // These are generated by Playwright e2e runs, or locked by Visual Studio
      // (.vs), and watching them makes Vite crash with EBUSY on Windows while
      // the files are being written.
      ignored: ['**/playwright-report/**', '**/test-results/**', '**/e2e/.data/**', '**/.vs/**'],
    },
  },
});
